### ISSUE TITLE
Move this project to an organization account

### ISSUE THREAD

**Issue by PeterDaveHello** [transmission-remote-gui/transmisson-remote-gui#1029]
I suggest we to move to an organization account, which provide more features, like team, thus we can tag different team by different purpose, e.g. `translation`, `build`, `core`, etc, also, it's more convenient to give permission to different members, to help integration more service, more than Travis CI, like issue management tool, etc, to improve the whole project management.

 To prevent breaking the programs, we can transfer this repository to the new organization, so that GitHub will automatically create redirects, and also, @leonsoft-kras can still fork it back to the personal account, so all the files can still be downloaded without any problem.

I've created @transmission-remote-gui and invited @leonsoft-kras , @antekgla to be the organization owner, who is most active in this project development recently, please join if you agree 😄 I think we can invite more people who helps translation, and maybe even create a static website for this project.

**Comment by PeterDaveHello** [comment]
I saw @leonsoft-kras joined 😃 
@leonsoft-kras would you please help transfer ownership of the repository to the organization? Thanks.

**Comment by rzcat** [comment]
I'm looking forward to have this project become part of the official transmission project...😅

**Comment by leonsoft-kras** [comment]
...please help transfer

but what should be done? Where to press?

**Comment by PeterDaveHello** [comment]
@leonsoft-kras it's in the project setting, there is a transfer option

**Comment by PeterDaveHello** [comment]
@leonsoft-kras just a reminder, once you transferred with success, please also forked the transferred repository to your personal account, so that we won't break the current users, thanks a lot.

**Comment by PeterDaveHello** [comment]
@rzcat not impossible, I also invited you :)

**Comment by leonsoft-kras** [comment]
What will happen to these addresses after the project is transferred? can I get an answer?
it depends on it - will all users be able to find out where the new versions of the programs are now located.

https://raw.githubusercontent.com/leonsoft-kras/transmisson-remote-gui/master/flags.zip
https://github.com/leonsoft-kras/transmisson-remote-gui/releases
https://raw.githubusercontent.com/leonsoft-kras/transmisson-remote-gui/master/VERSION.txt

I suggest studying this issue.
otherwise many users will think that the program is no longer updated.

**Comment by PeterDaveHello** [comment]
Don't worry, GitHub will redirect the links, see example here: https://github.com/IonicaBizau/cdnjs-importer/raw/master/package.json

**Comment by leonsoft-kras** [comment]
Nothing happens. What to enter?
![default](https://user-images.githubusercontent.com/11468577/32987195-d8e64934-cd16-11e7-9a1f-c9c63b65f12b.png)

**Comment by PeterDaveHello** [comment]
The first field: `transmisson-remote-gui`
The second: `transmission-remote-gui`

**Comment by PeterDaveHello** [comment]
It's done. Thanks @leonsoft-kras

**Comment by PeterDaveHello** [comment]
BTW guys you can setup your organization to be public here: https://github.com/orgs/transmission-remote-gui/people

**Comment by cfpp2p** [comment]
how to join?

**Comment by PeterDaveHello** [comment]
I've invited all the collaborators to join, if anyone wants to join, simply send two pull requests and get it merged, I'll invite you 😄

**Comment by antekgla** [comment]
I trying to push a commit (like I used to do) with Github Desktop and now I get a error: **"Authentication failed. You may not have permission to access the repository."**

**Comment by PeterDaveHello** [comment]
@antekgla I think it's my fault and I updated the permission of each team, please try again, thanks.

**Comment by antekgla** [comment]
Solved!
Thanks!

**Comment by rzcat** [comment]
anyone have both lazarus and delphi installed on one computer?
to maintain an old project, i have delphi installed. do they have conflicts?

**Comment by antekgla** [comment]
I have Delphi 7 and Lazarus installed in my system with Windows 7 and no problem.
Lazarus not interfere with anything. It is instaled in C:\lazarus by default and dont steal any file asociation (*.pas) from Delphi.
